### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by CaesarSP** [DakotaPride/Spectre#1]
Yeah... Is it possible for sleep related mods to be causing this?
After sleeping it gets fixed, as expected. 

![Captura de pantalla (270)](https://github.com/DakotaPride/Spectre/assets/138718742/2d15175a-3e91-487c-bedc-c6697693abf8)

**Comment by DakotaPride** [comment]
This was a bug that I kept on going back and forth on, unable to properly fix it, and was one of the reasons why the mod is now archived. Apologies for the issue, but I would highly suggest simply uninstalling the mod, as any version available to the public is unstable.

**Comment by CaesarSP** [comment]
Oh, I didn't notice the archive label when downloading. Sorry to bother. Thanks for the answer.
